# Generated by Django 4.1.2 on 2022-10-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
